### ISSUE TITLE
TODO) Est-ce qu'on préfère Ntro.appCloser().close() ou AppCloser.close() ?? 

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#31]
Peu importe le choix, il faut ensuite rentre ça uniforme

**Comment by Benjozork** [comment]
Je pense que `Ntro.appCloser().close()` serait plus approprié, pour éviter de polluer le namespace global avec trop de classes statiques. Comme ça `Ntro` serait utilisé pour la plupart des choses autant que possible.

**Comment by mathieu-bergeron** [comment]
Oui, bien d'accord! En plus en regroupant tout sous Ntro.XXX on a un auto-complétions des services de Ntro. C'est pratique et auto-documentant. Pour l'instant le seul que je garderais en statique est T.call()  (parce qu'il faut que ça soit rapide à écrire).
