### ISSUE TITLE
FIXME) les js sont pas dans le Docker

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#52]
Je pense qu'il faut faire la copie --from-build sinon ça copie du répertoire de la machine hôte, qui a pas nécessairement les bonnes versions (ou même pas de js du tout)

**Comment by mathieu-bergeron** [comment]
Il faut donc éditer le Dockerfile de aquiletour et tester

**Comment by LeducNic** [comment]
J'ai fixe dans ma branche.  J'ai aussi ajoute les donnees de test.

**Comment by mathieu-bergeron** [comment]
Super, merci!
