### ISSUE TITLE
Jalon 02, objectif 01) envoyer un courriel à partir de l'image aquiletour, en passant par l'image postfix

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#60]
Dans le docker-compose.yml il y a déjà une image postfix.

Il faut configurer pour qu'à partir de l'image aquiletour, on puisse faire

$ echo "TEST" | mail -s TEST mathieu.bergeron@cmontmorency.qc.ca 

et que ça envoie un courriel.

Il y a sûrement quelque config à faire:

* ouvrir le bon port chez OVH (?)
* configurer l'image postfix
* configurer l'image aquiletour pour que sont serveur smtp soit l'image postfix (Nicolas me dit que docker-compose configurer les images docker avec les bons noms de réseau, alors pas besoin de connaître leur IP)

**Comment by LeducNic** [comment]
Il n'y a pas d'image postfix pour l'instant, il faut la creer et la configurer.
1. Faire le Dockerfile dans le repertoire postfix
2. Ajouter postfix a docker-compose.yml
