### ISSUE TITLE
TODO) Config. de la sauvegarde pour images Docker

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#73]
À décider: Est-ce qu'on fait la sauvegarde du volume Docker ou est-ce qu'on se connecte à l'image pour "dumper" la DB??

Si on se connect pour dumper la DB, il faut une image Docker pour effectuer la sauvegarde (car la machine hôte ne devrais pas accéder directement à la DB).

**Comment by LeducNic** [comment]
L'image dummy a les clients pour mariadb et mongodb.
On peut la copier/renommer, ajouter les liens vers les volumes et le disque local et rouler la commande pour le dump.
