### ISSUE TITLE
ATTENTION) As-tu fait un rechercher-renommer dans tout le projet???

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#75]
en fusionnant, j'ai trouvé des appointmentDefinedMethods plutôt que userDefinedMethods

Et j'ai trouvé ceci dans les configs gradle:
    inputs.dir("${System.getProperty('appointment.home')}/.m2/repository/ca/ntro/ntro_core")
    inputs.dir("${System.getProperty('appointment.home')}/.m2/repository/ca/ntro/ntro_jsweet")
    inputs.dir("${System.getProperty('appointment.home')}/.m2/repository/ca/aquiletour/aquiletour_core")

Et ça devrait être 

    inputs.dir("${System.getProperty('user.home')}/.m2/repository/ca/ntro/ntro_core")
    inputs.dir("${System.getProperty('user.home')}/.m2/repository/ca/ntro/ntro_jsweet")
    inputs.dir("${System.getProperty('user.home')}/.m2/repository/ca/aquiletour/aquiletour_core")

**Comment by marbawws** [comment]
Oops, j'ai copier-coller et renommer les fichiers appointments pour créer les fichiers users. J'ai probablement fait une erreur dans le scope du renommage.

**Comment by mathieu-bergeron** [comment]
Oups ;-)

Tu me montreras ce que tu as fait, j'ai peut-être des suggestions sur comment procéder plus sécuritairement!
