### ISSUE TITLE
TODO) Créer une tâche JsonLoaderJSweet

### ISSUE THREAD

**Issue by mathieu-bergeron** [mathieu-bergeron/aquiletour2021#82]
Plutôt qu'utiliser JsonLoaderMemory (qui est Sync), on veut créer un JsonLoaderJSweet (qui est Async).

On ne veut pas utiliser Lang.await, mais plutôt créer notre tâche JsonLoaderJSweet qui sera insérée dans le graphe de tâche.  À terme, on va pouvoir afficher le graphe de tâches dans le client et c'est comme ça qu'on va déboguer.

Ce qu'il faut faire est donc très similaire à ResourceLoaderTaskJSweet.  On met le fetch dans la tâche et on appelle notifyTaskFinished() quand le fetch retourne.

**Comment by mathieu-bergeron** [comment]
En passant, pour l'erreur de compilation:

* c'est tsc qui donne l'erreur (mais c'est sourcemappé aux numéros de lignes Java)
* en utilisant Lang.await, il faut mettre async à quelque part. J'ai essayé en ajoutant @Async à la méthode fetchJsonObject, mais ça donnait quand même l'erreur. J'ai arrêté là ;-)

**Comment by Benjozork** [comment]
fait dans 88d75d5
